export default function TabelaBrasileirao() {
  return (
    <table className="tabela-brasileirao">
      <thead>
    <tr>
      <th>Clube</th>
      <th>Pts</th>
      <th>J</th>
      <th>VIT</th>
      <th>E</th>
      <th>DER</th>
      <th>GM</th>
      <th>GC</th>
      <th>SG</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Athlético-PR</td>
      <td>13</td>
      <td>6</td>
      <td>4</td>
      <td>1</td>
      <td>1</td>
      <td>9</td>
      <td>6</td>
      <td>3</td>
    </tr>
    <tr>
      <td>Bahia</td>
      <td>13</td>
      <td>6</td>
      <td>4</td>
      <td>1</td>
      <td>1</td>
      <td>8</td>
      <td>5</td>
      <td>3</td>
    </tr>
    <tr>
      <td>Flamengo</td>
      <td>11</td>
      <td>6</td>
      <td>3</td>
      <td>2</td>
      <td>1</td>
      <td>7</td>
      <td>5</td>
      <td>2</td>
    </tr>
    <tr>
      <td>Botafogo</td>
      <td>11</td>
      <td>6</td>
      <td>3</td>
      <td>2</td>
      <td>1</td>
      <td>7</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <td>São Paulo</td>
      <td>10</td>
      <td>6</td>
      <td>3</td>
      <td>1</td>
      <td>2</td>
      <td>6</td>
      <td>3</td>
      <td>3</td>
    </tr>
    <tr>
      <td>Cruzeiro</td>
      <td>10</td>
      <td>6</td>
      <td>3</td>
      <td>1</td>
      <td>2</td>
      <td>6</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <td>Atlético-MG</td>
      <td>9</td>
      <td>6</td>
      <td>2</td>
      <td>3</td>
      <td>1</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
    </tr>
    <tr>
      <td>Bragantino</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>8</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Palmeiras</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Internacional</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
      <td>7</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Fortaleza</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
      <td>7</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Grêmio</td>
      <td>8</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>4</td>
      <td>6</td>
      <td>-2</td>
    </tr>
    <tr>
      <td>Vasco da Gama</td>
      <td>7</td>
      <td>6</td>
      <td>2</td>
      <td>1</td>
      <td>3</td>
      <td>5</td>
      <td>10</td>
      <td>-5</td>
    </tr>
    <tr>
      <td>Criciúma</td>
      <td>6</td>
      <td>6</td>
      <td>1</td>
      <td>3</td>
      <td>2</td>
      <td>6</td>
      <td>7</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Juventude</td>
      <td>6</td>
      <td>6</td>
      <td>1</td>
      <td>3</td>
      <td>2</td>
      <td>4</td>
      <td>7</td>
      <td>-3</td>
    </tr>
    <tr>
      <td>Corinthians</td>
      <td>5</td>
      <td>6</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>6</td>
      <td>8</td>
      <td>-2</td>
    </tr>
    <tr>
      <td>Fluminense</td>
      <td>5</td>
      <td>6</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
      <td>6</td>
      <td>-2</td>
    </tr>
    <tr>
      <td>EC Vitória</td>
      <td>5</td>
      <td>6</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>3</td>
      <td>5</td>
      <td>-2</td>
    </tr>
    <tr>
      <td>Atlético-GO</td>
      <td>4</td>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>4</td>
      <td>5</td>
      <td>8</td>
      <td>-3</td>
    </tr>
    <tr>
      <td>Cuiabá</td>
      <td>0</td>
      <td>6</td>
      <td>0</td>
      <td>0</td>
      <td>6</td>
      <td>2</td>
      <td>12</td>
      <td>-10</td>
    </tr>
  </tbody>
    </table>
  );
}
//JOGA


